- name: Docker Container Status in Ansible
  hosts: "{{hostnames}}"
  tasks:
    - name: List all Docker containers
      command: docker ps -a
      register: docker_containers
    - debug:
        var: docker_containers.stdout_lines