- name: Docker Container Status in Ansible
  become: true
  become_method: sudo
  hosts: "{{hostnames}}"
  tasks:
    - name: List all Docker containers
      #command: docker ps -a --format "table {{.Names}}\t{{.Status}}"
      command: /usr/bin/docker ps -a --format "table {{ '{{' }} .Names {{ '}}' }}\t{{ '{{' }} .Status {{ '}}' }}"
      register: docker_containers
      tags:
      - always
    - debug:
        var: docker_containers.stdout_lines    
      tags:
      - always
    - name: List all Docker containers 2
      #command: docker ps -a --format "table {{.Names}}\t{{.Status}}"
      command: /usr/bin/docker ps -a --format "table {{ '{{' }} .Names {{ '}}' }}\t{{ '{{' }} .Status {{ '}}' }}"
      register: docker_containers2
      tags:
      - always2
    - debug:
        var: docker_containers2.stdout_lines    
      tags:
      - always2
