---
  #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/reboot_module.html#examples
  - name: Reboot host and send a message
    hosts: "{{hostnames}}"
    become: true
    tasks:
    - name: Delay Reboot by 1m, Reboot machine and send a message
      ansible.builtin.reboot:
        pre_reboot_delay: 70
        msg: "Rebooting machine in 70 seconds"
    - name: Check the Uptime of the servers
        shell: uptime
        register: Uptime
    - debug: msg={{Uptime.stdout}}
